---
- name: update apt
  become: true
  raw: |
    apt update && apt -y dist-upgrade
- name: Install a list of basic packages
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - software-properties-common
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - xz-utils
    - liblzma-dev
    - libncurses5-dev 
    - libncursesw5-dev
    - tk-dev
    - libffi-dev

- name: clone vundle
  git: repo=https://github.com/VundleVim/Vundle.vim
       dest=/home/{{ username }}/.vim/bundle/Vundle.vim
       update=no

- block:
  - name: install locale
    become: true
    apt:
      name: locales
      update_cache: yes

  - name: install main language
    become: true
    locale_gen:
      name: "{{ main_locale }}"
      state: present

  - name: Set default locale to en_US.UTF-8
    debconf:
      name: locales
      question: locales/default_environment_locale
      value: en_US.UTF-8
      vtype: select

- name: install pip3
  when: ansible_python_interpreter == '/usr/bin/python3'
  become: true
  apt:
    name: python3-pip 

- name: upgrade pip3
  when: ansible_python_interpreter == '/usr/bin/python3'
  become: true
  shell: pip3 install pip --upgrade

- name: install pip2
  when: ansible_python_interpreter != '/usr/bin/python3'
  become: true
  apt:
    name: python-pip 

- name: upgrade pip2
  when: ansible_python_interpreter != '/usr/bin/python3'
  become: true
  shell: pip install pip --upgrade

    #- name: upgrade pip
    #  pip: 
    #    name: pip
    #    state: latest
    #    extra_args: --upgrade
