- file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755

- name: get pyenv installer
  get_url:
    url: https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
    dest: "{{ tmp_dir }}/pyenv-installer"
    mode: 0755

- name: check if .pyenv folder exists
  stat: path=/home/{{ username }}/.pyenv
  register: pyenv

- name: install pyenv
  when: pyenv.stat.exists != True
  raw: "{{ usershell | default('bash') }} {{ tmp_dir }}/pyenv-installer"

- name: append pyenv settings to shell resource file
  blockinfile:
    path: /home/{{ username }}/{{ '.zshrc' if usershell == 'zsh' else '.bashrc' }}
    block: |
      export PATH="/home/{{ username }}/.pyenv/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"

- name: install specific python
  when: pyenv_default_install
  shell: source /home/{{ username }}/{{ '.zshrc' if usershell == 'zsh' else '.bashrc' }} && env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install {{ pyenv_default_python | default('3.6.6') }} && pyenv global {{ pyenv_default_python | default('3.6.6') }}
  args:
     executable: "{{ '/usr/bin/zsh' if usershell == 'zsh' else '/bin/bash' }}"

- name: pip upgrade
  when: pyenv_default_install
  shell: source /home/{{ username }}/{{ '.zshrc' if usershell == 'zsh' else '.bashrc' }} && pip install --upgrade pip
  args:
     executable: "{{ '/usr/bin/zsh' if usershell == 'zsh' else '/bin/bash' }}"
