- file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: 0755

- name: get gvm installer
  get_url:
    url: https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer
    dest: "/home/{{ username }}/tmp/gvm-installer"
    mode: 0755

- name: check if .gvm exists
  stat: path=/home/{{ username }}/.gvm
  register: gvm

- name: install gvm
  when: gvm.stat.exists == False
  raw: "{{ usershell | default('bash') }} {{ tmp_dir }}/gvm-installer"
